- menu_name: "Regulament"

- name: "Termeni si conditii"
  url: "https://costiui.ml/termeni-si-conditii/"
  title: "Termeni si conditii"

- name: "Politica de Confidentialitate"
  url: "https://costiui.ml/politica-de-confidentialitate/"
  title: "Politica de Confidentialitate"
