- menu_name: "Services"

- name: "Termeni si conditii"
  url: "https://www.costiui.net/termeni-si-conditii/"
  title: "Termeni si conditii"

- name: "Politica de Confidentialitate"
  url: "https://www.costiui.net/politica-de-confidentialitate/"
  title: "Politica de Confidentialitate"
